### PR TITLE
Added confirmations to Player remove award, unit, title, strip all awards

### PR DESCRIPTION
**Pull request by jrtaylor-com**
Confirmation dialog testing required

### CODE REVIEW

**Comment by kenwalker** [comment]
Historical imports should have the prompt as well

**Comment by kenwalker** [comment]
Other than the above comment, looks good

**Review by kenwalker — APPROVED** [review]

**Comment by jrtaylor-com** [comment]
@kenwalker went ahead and added the suggested confirm for Historic Import so we can wrap up the underlying issue

**Comment by kenwalker** [comment]
> @kenwalker went ahead and added the suggested confirm for Historic Import so we can wrap up the underlying issue

Looks good, tested

**Pull request merged**
