### PR TITLE
Dues for life on player page expiry hidden and highlighted

### PR DESCRIPTION
**Pull request by tzulah**

### CODE REVIEW

**Comment by kenwalker** [comment]
The player page seems good

**Review by kenwalker — APPROVED** [review]
Don't close the issue yet since the reports don't hide the dates for players with dues for life yet but this change for the player page is good

**Comment by jrtaylor-com** [comment]
> Don't close the issue yet since the reports don't hide the dates for players with dues for life yet but this change for the player page is good

These should be fixed on the other branch `issue272-update-old-reports-dues-paid_col`

**Comment by tzulah** [comment]
Is there another place I need to work on, or is it handled already?

**Comment by jrtaylor-com** [comment]
> Is there another place I need to work on, or is it handled already?

No this is good, I'll merge it this evening for public testing

**Pull request merged**
